//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeurTaqnshare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defi
    {
        public Defi()
        {
            this.Composers = new HashSet<Composer>();
        }
    
        public int id_defi { get; set; }
        public string id_utilisateur { get; set; }
        public string id_adversaire_defi { get; set; }
        public string nom_defi { get; set; }
        public Nullable<decimal> score_utilisateur_defi { get; set; }
        public Nullable<decimal> score_adversaire_defi { get; set; }
        public Nullable<bool> resolu { get; set; }
        public string chemin_image_defi { get; set; }
    
        public virtual ICollection<Composer> Composers { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
