//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeurTaqnshare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Piece
    {
        public Piece()
        {
            this.Composers = new HashSet<Composer>();
        }
    
        public int id_piece { get; set; }
    
        public virtual ICollection<Composer> Composers { get; set; }
    }
}
