//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeurTaqnshare
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaqnshareEntities : DbContext, IDisposable
    {
        public TaqnshareEntities()
            : base("name=TaqnshareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Composer> Composers { get; set; }
        public virtual DbSet<Defi> Defis { get; set; }
        public virtual DbSet<Filtre> Filtres { get; set; }
        public virtual DbSet<Piece> Pieces { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
        public void Dispose()
        {
            throw new NotImplementedException();
        }
    }
}
