//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeurTaqnshare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public Utilisateur()
        {
            this.Defis = new HashSet<Defi>();
        }
    
        public string id_utilisateur { get; set; }
        public string nom_utilisateur { get; set; }
        public string prenom_utilisateur { get; set; }
        public Nullable<decimal> nombre_partie_utilisateur { get; set; }
        public Nullable<decimal> score_total_utilisateur { get; set; }
    
        public virtual ICollection<Defi> Defis { get; set; }
    }
}
