//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_taqnshareEntities : DbContext
    {
        public db_taqnshareEntities()
            : base("name=db_taqnshareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<composer> composers { get; set; }
        public virtual DbSet<defi> defis { get; set; }
        public virtual DbSet<filtre> filtres { get; set; }
        public virtual DbSet<piece> pieces { get; set; }
        public virtual DbSet<utilisateur> utilisateurs { get; set; }
    }
}
