//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class defi
    {
        public defi()
        {
            this.composers = new HashSet<composer>();
        }
    
        public int id_defi { get; set; }
        public string id_utilisateur { get; set; }
        public string nom_defi { get; set; }
        public string id_adversaire_defi { get; set; }
        public Nullable<decimal> score_adversaire_defi { get; set; }
        public Nullable<decimal> score_utilisateur_defi { get; set; }
        public string chemin_image_defi { get; set; }
        public Nullable<decimal> nombre_decoupage_image_defi { get; set; }
        public Nullable<bool> resolu { get; set; }
    
        public virtual ICollection<composer> composers { get; set; }
        public virtual utilisateur utilisateur { get; set; }
    }
}
