//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class piece
    {
        public piece()
        {
            this.composers = new HashSet<composer>();
        }
    
        public string id_piece { get; set; }
    
        public virtual ICollection<composer> composers { get; set; }
    }
}
