//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilisateur
    {
        public utilisateur()
        {
            this.defis = new HashSet<defi>();
        }
    
        public string id_utilisateur { get; set; }
        public Nullable<decimal> nombre_partie_utilisateur { get; set; }
        public Nullable<decimal> score_total_utilisateur { get; set; }
    
        public virtual ICollection<defi> defis { get; set; }
    }
}
